# Docker Compose configuration
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - volume_wordpress:/var/www/wordpress
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    ports:
      - "9000:9000"
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    secrets:
      - db_password
      - db_password
    volumes:
      - volume_wordpress:/var/www/wordpress
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - volume_mariadb:/var/lib/mysql
  sitatic_site:
    build: ./requirements/bonus/sitatic_site
    container_name: sitatic_site
    image: sitatic_site
    ports:
      - "8081:8081"
    restart: always
    networks:
      - inception_network
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    ports:
      - "8083:8083"
    restart: always
    networks:
      - inception_network
networks:
  inception_network:
    driver: bridge
volumes:
  volume_mariadb:
    driver: local
    driver_opts:
      device: /home/omar/data/mariadb
      type: none
      o: bind
  volume_wordpress:
    driver: local
    driver_opts:
      device: /home/omar/data/wordpress
      type: none
      o: bind
secrets:
  db_password:
    file: ../secrets/db_password.txt
  user_password:
    file: ../secrets/user_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt