# docker-comopse version (docker version beyond 19.03.0+ <-> compose version 3.8v)
version: "3.8"

# definition fo services
services:
  # nginx
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - volume_wordpress:/var/www/wordpress
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    ports:
      - "9000:9000"
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - volume_mariadb:/var/lib/mysql

networks:
  inception_network:
    driver: bridge
volumes:
  volume_mariadb:
    driver_opts:
      device: /var/lib/mysql
      type: none
      o: bind

  volume_wordpress:
    driver_opts:
      device: /var/www/wordpress
      type: none
      o: bind